baseURL = 'https://derekcuevas.github.io/'
languageCode = 'en-us'
title = 'FYGT'
theme = 'archie'
copyright = "© Derek Cuevas"
pygmentsstyle = "github-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
enableGitInfo = true
googleAnalytics = "G-F2E1LBE19M"

[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = ["lastmod", ":git", "date", "publishDate"]

[taxonomies]
author = "authors"
tag = "tags"

[params]
mode = "toggle"
useCDN = false
subtitle = "An automated AI generated tech blog ([source code](https://github.com/DerekCuevas/derekcuevas.github.io))"
schedule = 86400000
customcss = ["css/overrides.css"]

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/derekcuevas"

[[menu.main]]
name = "About"
url = "/about"
weight = 1

[[menu.main]]
name = "Résumé"
url = "/resume"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "All Articles"
url = "/posts"
weight = 4
