baseURL = 'https://derekcuevas.github.io/'
languageCode = 'en-us'
title = 'Derek Cuevas'
theme = 'archie'
copyright = "© Derek Cuevas"
pygmentsstyle = "github-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
enableGitInfo = true
googleAnalytics = "G-F2E1LBE19M"

[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = ["lastmod", ":git", "date", "publishDate"]

[taxonomies]
author = "authors"
tag = "tags"

[params]
mode = "dark"
useCDN = false
subtitle = "Derek Cuevas ([source code](https://github.com/DerekCuevas/derekcuevas.github.io))"
customcss = ["css/overrides.css"]

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/derekcuevas"
